CREATE TABLE log (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	date_visited timestamp NULL,
	region varchar(20) NOT NULL,
	url varchar(255) NOT NULL,
	user_id varchar(36) NOT NULL,
	CONSTRAINT log_pkey PRIMARY KEY (id)
);